[package]
name = "remote-pty-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.1"
libc = "0.2.90"
lazy_static = "1.4.0"
rand = "0.8.3"
