name: build

on:
  - push

jobs:
  build:
    name: ${{ matrix.arch }} build (${{ matrix.os }})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux
            arch: x86_64
            extra_apt_packages: ""
          - os: ubuntu-22.04-arm
            target: linux
            arch: aarch64
            extra_apt_packages: musl-dev
    steps:
    - uses: actions/checkout@v3
    - name: install apt packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq build-essential gpg ca-certificates curl file autoconf zip netcat-openbsd lsof linux-headers-generic ${{ matrix.extra_apt_packages }}
    - name: install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
        $HOME/.cargo/bin/rustup target add ${{matrix.arch}}-unknown-linux-musl
        $HOME/.cargo/bin/rustup target add ${{matrix.arch}}-unknown-linux-gnu
    - name: test-remote-pty
      run: |
        cargo test --release --target ${{matrix.arch}}-unknown-linux-gnu
      shell: bash
      env:
        RUST_BACKTRACE: 1
    - name: build-remote-pty-slave-static
      run: |
        ./remote-pty-slave/build/build-static.sh ${{matrix.arch}}-unknown-linux-musl
      shell: bash
    - name: build-remote-pty-slave-shared
      run: |
        ./remote-pty-slave/build/build-shared.sh ${{matrix.arch}}-unknown-linux-gnu
      shell: bash
    - name: build-remote-pty-master
      run: |
        cargo build --release --target ${{matrix.arch}}-unknown-linux-gnu
      shell: bash
      working-directory: ./remote-pty-master
    - name: build-bash
      run: |
        ./build.sh ${{matrix.target}} ${{matrix.arch}}
        cp -v releases/bash releases/bash-${{matrix.target}}-${{matrix.arch}}
        cp -v releases/bash releases/bash-${{matrix.target}}-${{matrix.arch}}-stripped
        strip releases/bash-${{matrix.target}}-${{matrix.arch}}-stripped
        rm -f releases/bash
      working-directory: bash-static-remote
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: bash-rpty-${{matrix.target}}-${{matrix.arch}}
        path: bash-static-remote/releases/bash-${{matrix.target}}-${{matrix.arch}}
    - uses: actions/upload-artifact@v4
      with:
        name: bash-rpty-${{matrix.target}}-${{matrix.arch}}-stripped
        path: bash-static-remote/releases/bash-${{matrix.target}}-${{matrix.arch}}-stripped
    - uses: actions/upload-artifact@v4
      with:
        name: rpty-master-${{matrix.arch}}
        path: target/${{matrix.arch}}-unknown-${{matrix.target}}-gnu/release/remote-pty-master
    - uses: actions/upload-artifact@v4
      with:
        name: librpty_slave-${{matrix.target}}-${{matrix.arch}}.a
        path: target/${{matrix.arch}}-unknown-${{matrix.target}}-musl/release/libremote_pty_slave.linked.a
    - uses: actions/upload-artifact@v4
      with:
        name: librpty_slave-${{matrix.target}}-${{matrix.arch}}.so
        path: target/${{matrix.arch}}-unknown-${{matrix.target}}-gnu/release/libremote_pty_slave.linked.so
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Deploy artifact to https://rpty-artifacts.tunshell.com
    - name: Deploy to S3
      run: >
        aws s3 cp --recursive bash-static-remote/releases/ s3://rpty-artifacts/
        --acl=public-read 
        --cache-control max-age=31536000
        --metadata-directive REPLACE
      shell: bash

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id=E2J9NPXI4IHDJA --paths '/*'
